### ISSUE TITLE
Any chance to remove click dependency?

### ISSUE THREAD

**Issue by YLTsai0609** [ryanchao2012/airfly#1]
Currently, I'm using this awesome package. However, I faced a problem when resolving package dependency.

My example command below
```
(base) user@workstation:path$ poetry add airfly
Using version ^0.6.3 for airfly

Updating dependencies
Resolving dependencies... (1.9s)

  SolverProblemError

  Because no versions of airfly match >0.6.3,<0.7.0
   and airfly (0.6.3) depends on click (>=8.0.1,<9.0.0), airfly (>=0.6.3,<0.7.0) requires click (>=8.0.1,<9.0.0).
  And because elasticsearch-loader (0.6.0) depends on click (7.0), airfly (>=0.6.3,<0.7.0) is incompatible with elasticsearch-loader (0.6.0).
  So, because `your_repo_name` depends on both elasticsearch-loader (0.6.0) and airfly (^0.6.3), version solving failed.
```

It seems that there is a `click` dependency issue.

Is there a chance to remove the `click` dependency?

**Comment by ryanchao2012** [comment]
Thank you for reporting this issue,
it seems we could loose some package dependencies in `airfly`
since we only need the very basic functions from them.

I will change the package deps as follows:
```
[tool.poetry.dependencies]
python = "^3.7"
asttrs = "^0.6.0"
attrs = "*"
black = "*"
click = "*"
networkx = "*"
isort = "*"
regex = "*"
```
For now, just let the clients to resolve them in their environment.

**Comment by ryanchao2012** [comment]
https://github.com/ryanchao2012/airfly/pull/2

**Comment by ryanchao2012** [comment]
These changes will be released in `0.7.0`

**Comment by ryanchao2012** [comment]
These changes will be released in `0.7.2`

**Comment by YLTsai0609** [comment]
Thanks for your help!

**Comment by ryanchao2012** [comment]
closed
